export const countries = [
  { value: 'AFG', label: 'Afghanistan' },
  { value: 'ALB', label: 'Albania' },
  { value: 'DZA', label: 'Algeria' },
  { value: 'ASM', label: 'American Samoa' },
  { value: 'AND', label: 'Andorra' },
  { value: 'AGO', label: 'Angola' },
  { value: 'AIA', label: 'Anguilla' },
  { value: 'ATA', label: 'Antarctica' },
  { value: 'ATG', label: 'Antigua and Barbuda' },
  { value: 'ARG', label: 'Argentina' },
  { value: 'ARM', label: 'Armenia' },
  { value: 'ABW', label: 'Aruba' },
  { value: 'AUS', label: 'Australia' },
  { value: 'AUT', label: 'Austria' },
  { value: 'AZE', label: 'Azerbaijan' },
  { value: 'BHS', label: 'Bahamas (the)' },
  { value: 'BHR', label: 'Bahrain' },
  { value: 'BGD', label: 'Bangladesh' },
  { value: 'BRB', label: 'Barbados' },
  { value: 'BLR', label: 'Belarus' },
  { value: 'BEL', label: 'Belgium' },
  { value: 'BLZ', label: 'Belize' },
  { value: 'BEN', label: 'Benin' },
  { value: 'BMU', label: 'Bermuda' },
  { value: 'BTN', label: 'Bhutan' },
  { value: 'BOL', label: 'Bolivia (Plurinational State of)' },
  { value: 'BES', label: 'Bonaire, Sint Eustatius and Saba' },
  { value: 'BIH', label: 'Bosnia and Herzegovina' },
  { value: 'BWA', label: 'Botswana' },
  { value: 'BVT', label: 'Bouvet Island' },
  { value: 'BRA', label: 'Brazil' },
  { value: 'IOT', label: 'British Indian Ocean Territory (the)' },
  { value: 'BRN', label: 'Brunei Darussalam' },
  { value: 'BGR', label: 'Bulgaria' },
  { value: 'BFA', label: 'Burkina Faso' },
  { value: 'BDI', label: 'Burundi' },
  { value: 'CPV', label: 'Cabo Verde' },
  { value: 'KHM', label: 'Cambodia' },
  { value: 'CMR', label: 'Cameroon' },
  { value: 'CAN', label: 'Canada' },
  { value: 'CYM', label: 'Cayman Islands (the)' },
  { value: 'CAF', label: 'Central African Republic (the)' },
  { value: 'TCD', label: 'Chad' },
  { value: 'CHL', label: 'Chile' },
  { value: 'CHN', label: 'China' },
  { value: 'CXR', label: 'Christmas Island' },
  { value: 'CCK', label: 'Cocos (Keeling) Islands (the)' },
  { value: 'COL', label: 'Colombia' },
  { value: 'COM', label: 'Comoros (the)' },
  { value: 'COD', label: 'Congo (the Democratic Republic of the)' },
  { value: 'COG', label: 'Congo (the)' },
  { value: 'COK', label: 'Cook Islands (the)' },
  { value: 'CRI', label: 'Costa Rica' },
  { value: 'HRV', label: 'Croatia' },
  { value: 'CUB', label: 'Cuba' },
  { value: 'CUW', label: 'Curaçao' },
  { value: 'CYP', label: 'Cyprus' },
  { value: 'CZE', label: 'Czechia' },
  { value: 'CIV', label: "Côte d'Ivoire" },
  { value: 'DNK', label: 'Denmark' },
  { value: 'DJI', label: 'Djibouti' },
  { value: 'DMA', label: 'Dominica' },
  { value: 'DOM', label: 'Dominican Republic (the)' },
  { value: 'ECU', label: 'Ecuador' },
  { value: 'EGY', label: 'Egypt' },
  { value: 'SLV', label: 'El Salvador' },
  { value: 'GNQ', label: 'Equatorial Guinea' },
  { value: 'ERI', label: 'Eritrea' },
  { value: 'EST', label: 'Estonia' },
  { value: 'SWZ', label: 'Eswatini' },
  { value: 'ETH', label: 'Ethiopia' },
  { value: 'FLK', label: 'Falkland Islands (the) [Malvinas]' },
  { value: 'FRO', label: 'Faroe Islands (the)' },
  { value: 'FJI', label: 'Fiji' },
  { value: 'FIN', label: 'Finland' },
  { value: 'FRA', label: 'France' },
  { value: 'GUF', label: 'French Guiana' },
  { value: 'PYF', label: 'French Polynesia' },
  { value: 'ATF', label: 'French Southern Territories (the)' },
  { value: 'GAB', label: 'Gabon' },
  { value: 'GMB', label: 'Gambia (the)' },
  { value: 'GEO', label: 'Georgia' },
  { value: 'DEU', label: 'Germany' },
  { value: 'GHA', label: 'Ghana' },
  { value: 'GIB', label: 'Gibraltar' },
  { value: 'GRC', label: 'Greece' },
  { value: 'GRL', label: 'Greenland' },
  { value: 'GRD', label: 'Grenada' },
  { value: 'GLP', label: 'Guadeloupe' },
  { value: 'GUM', label: 'Guam' },
  { value: 'GTM', label: 'Guatemala' },
  { value: 'GGY', label: 'Guernsey' },
  { value: 'GIN', label: 'Guinea' },
  { value: 'GNB', label: 'Guinea-Bissau' },
  { value: 'GUY', label: 'Guyana' },
  { value: 'HTI', label: 'Haiti' },
  { value: 'HMD', label: 'Heard Island and McDonald Islands' },
  { value: 'VAT', label: 'Holy See (the)' },
  { value: 'HND', label: 'Honduras' },
  { value: 'HKG', label: 'Hong Kong' },
  { value: 'HUN', label: 'Hungary' },
  { value: 'ISL', label: 'Iceland' },
  { value: 'IND', label: 'India' },
  { value: 'IDN', label: 'Indonesia' },
  { value: 'IRN', label: 'Iran (Islamic Republic of)' },
  { value: 'IRQ', label: 'Iraq' },
  { value: 'IRL', label: 'Ireland' },
  { value: 'IMN', label: 'Isle of Man' },
  { value: 'ISR', label: 'Israel' },
  { value: 'ITA', label: 'Italy' },
  { value: 'JAM', label: 'Jamaica' },
  { value: 'JPN', label: 'Japan' },
  { value: 'JEY', label: 'Jersey' },
  { value: 'JOR', label: 'Jordan' },
  { value: 'KAZ', label: 'Kazakhstan' },
  { value: 'KEN', label: 'Kenya' },
  { value: 'KIR', label: 'Kiribati' },
  { value: 'PRK', label: "Korea (the Democratic People's Republic of)" },
  { value: 'KOR', label: 'Korea (the Republic of)' },
  { value: 'KWT', label: 'Kuwait' },
  { value: 'KGZ', label: 'Kyrgyzstan' },
  { value: 'LAO', label: "Lao People's Democratic Republic (the)" },
  { value: 'LVA', label: 'Latvia' },
  { value: 'LBN', label: 'Lebanon' },
  { value: 'LSO', label: 'Lesotho' },
  { value: 'LBR', label: 'Liberia' },
  { value: 'LBY', label: 'Libya' },
  { value: 'LIE', label: 'Liechtenstein' },
  { value: 'LTU', label: 'Lithuania' },
  { value: 'LUX', label: 'Luxembourg' },
  { value: 'MAC', label: 'Macao' },
  { value: 'MDG', label: 'Madagascar' },
  { value: 'MWI', label: 'Malawi' },
  { value: 'MYS', label: 'Malaysia' },
  { value: 'MDV', label: 'Maldives' },
  { value: 'MLI', label: 'Mali' },
  { value: 'MLT', label: 'Malta' },
  { value: 'MHL', label: 'Marshall Islands (the)' },
  { value: 'MTQ', label: 'Martinique' },
  { value: 'MRT', label: 'Mauritania' },
  { value: 'MUS', label: 'Mauritius' },
  { value: 'MYT', label: 'Mayotte' },
  { value: 'MEX', label: 'Mexico' },
  { value: 'FSM', label: 'Micronesia (Federated States of)' },
  { value: 'MDA', label: 'Moldova (the Republic of)' },
  { value: 'MCO', label: 'Monaco' },
  { value: 'MNG', label: 'Mongolia' },
  { value: 'MNE', label: 'Montenegro' },
  { value: 'MSR', label: 'Montserrat' },
  { value: 'MAR', label: 'Morocco' },
  { value: 'MOZ', label: 'Mozambique' },
  { value: 'MMR', label: 'Myanmar' },
  { value: 'NAM', label: 'Namibia' },
  { value: 'NRU', label: 'Nauru' },
  { value: 'NPL', label: 'Nepal' },
  { value: 'NLD', label: 'Netherlands (the)' },
  { value: 'NCL', label: 'New Caledonia' },
  { value: 'NZL', label: 'New Zealand' },
  { value: 'NIC', label: 'Nicaragua' },
  { value: 'NER', label: 'Niger (the)' },
  { value: 'NGA', label: 'Nigeria' },
  { value: 'NIU', label: 'Niue' },
  { value: 'NFK', label: 'Norfolk Island' },
  { value: 'MNP', label: 'Northern Mariana Islands (the)' },
  { value: 'NOR', label: 'Norway' },
  { value: 'OMN', label: 'Oman' },
  { value: 'PAK', label: 'Pakistan' },
  { value: 'PLW', label: 'Palau' },
  { value: 'PSE', label: 'Palestine, State of' },
  { value: 'PAN', label: 'Panama' },
  { value: 'PNG', label: 'Papua New Guinea' },
  { value: 'PRY', label: 'Paraguay' },
  { value: 'PER', label: 'Peru' },
  { value: 'PHL', label: 'Philippines (the)' },
  { value: 'PCN', label: 'Pitcairn' },
  { value: 'POL', label: 'Poland' },
  { value: 'PRT', label: 'Portugal' },
  { value: 'PRI', label: 'Puerto Rico' },
  { value: 'QAT', label: 'Qatar' },
  { value: 'MKD', label: 'Republic of North Macedonia' },
  { value: 'ROU', label: 'Romania' },
  { value: 'RUS', label: 'Russian Federation (the)' },
  { value: 'RWA', label: 'Rwanda' },
  { value: 'REU', label: 'Réunion' },
  { value: 'BLM', label: 'Saint Barthélemy' },
  { value: 'SHN', label: 'Saint Helena, Ascension and Tristan da Cunha' },
  { value: 'KNA', label: 'Saint Kitts and Nevis' },
  { value: 'LCA', label: 'Saint Lucia' },
  { value: 'MAF', label: 'Saint Martin (French part)' },
  { value: 'SPM', label: 'Saint Pierre and Miquelon' },
  { value: 'VCT', label: 'Saint Vincent and the Grenadines' },
  { value: 'WSM', label: 'Samoa' },
  { value: 'SMR', label: 'San Marino' },
  { value: 'STP', label: 'Sao Tome and Principe' },
  { value: 'SAU', label: 'Saudi Arabia' },
  { value: 'SEN', label: 'Senegal' },
  { value: 'SRB', label: 'Serbia' },
  { value: 'SYC', label: 'Seychelles' },
  { value: 'SLE', label: 'Sierra Leone' },
  { value: 'SGP', label: 'Singapore' },
  { value: 'SXM', label: 'Sint Maarten (Dutch part)' },
  { value: 'SVK', label: 'Slovakia' },
  { value: 'SVN', label: 'Slovenia' },
  { value: 'SLB', label: 'Solomon Islands' },
  { value: 'SOM', label: 'Somalia' },
  { value: 'ZAF', label: 'South Africa' },
  { value: 'SGS', label: 'South Georgia and the South Sandwich Islands' },
  { value: 'SSD', label: 'South Sudan' },
  { value: 'ESP', label: 'Spain' },
  { value: 'LKA', label: 'Sri Lanka' },
  { value: 'SDN', label: 'Sudan (the)' },
  { value: 'SUR', label: 'Suriname' },
  { value: 'SJM', label: 'Svalbard and Jan Mayen' },
  { value: 'SWE', label: 'Sweden' },
  { value: 'CHE', label: 'Switzerland' },
  { value: 'SYR', label: 'Syrian Arab Republic' },
  { value: 'TWN', label: 'Taiwan (Province of China)' },
  { value: 'TJK', label: 'Tajikistan' },
  { value: 'TZA', label: 'Tanzania, United Republic of' },
  { value: 'THA', label: 'Thailand' },
  { value: 'TLS', label: 'Timor-Leste' },
  { value: 'TGO', label: 'Togo' },
  { value: 'TKL', label: 'Tokelau' },
  { value: 'TON', label: 'Tonga' },
  { value: 'TTO', label: 'Trinidad and Tobago' },
  { value: 'TUN', label: 'Tunisia' },
  { value: 'TUR', label: 'Turvalue' },
  { value: 'TKM', label: 'Turkmenistan' },
  { value: 'TCA', label: 'Turks and Caicos Islands (the)' },
  { value: 'TUV', label: 'Tuvalu' },
  { value: 'UGA', label: 'Uganda' },
  { value: 'UKR', label: 'Ukraine' },
  { value: 'ARE', label: 'United Arab Emirates (the)' },
  { value: 'GBR', label: 'United Kingdom of Great Britain and Northern Ireland (the)' },
  { value: 'UMI', label: 'United States Minor Outlying Islands (the)' },
  { value: 'USA', label: 'United States of America (the)' },
  { value: 'URY', label: 'Uruguay' },
  { value: 'UZB', label: 'Uzbekistan' },
  { value: 'VUT', label: 'Vanuatu' },
  { value: 'VEN', label: 'Venezuela (Bolivarian Republic of)' },
  { value: 'VNM', label: 'Viet Nam' },
  { value: 'VGB', label: 'Virgin Islands (British)' },
  { value: 'VIR', label: 'Virgin Islands (U.S.)' },
  { value: 'WLF', label: 'Wallis and Futuna' },
  { value: 'ESH', label: 'Western Sahara' },
  { value: 'YEM', label: 'Yemen' },
  { value: 'ZMB', label: 'Zambia' },
  { value: 'ZWE', label: 'Zimbabwe' },
  { value: 'ALA', label: 'Åland Islands' },
]

export const countriesFR = [
  { value: 'AFG', label: 'Afghanistan' },
  { value: 'ALB', label: 'Albanie' },
  { value: 'DZA', label: 'Algérie' },
  { value: 'ASM', label: 'Samoa américaines' },
  { value: 'AND', label: 'Andorre' },
  { value: 'AGO', label: 'Angola' },
  { value: 'AIA', label: 'Anguilla' },
  { value: 'ATA', label: 'Antarctique' },
  { value: 'ATG', label: 'Antigua-et-Barbuda' },
  { value: 'ARG', label: 'Argentine' },
  { value: 'ARM', label: 'Arménie' },
  { value: 'ABW', label: 'Aruba' },
  { value: 'AUS', label: 'Australie' },
  { value: 'AUT', label: 'Autriche' },
  { value: 'AZE', label: 'Azerbaïdjan' },
  { value: 'BHS', label: 'Bahamas (les)' },
  { value: 'BHR', label: 'Bahreïn' },
  { value: 'BGD', label: 'Bangladesh' },
  { value: 'BRB', label: 'Barbade' },
  { value: 'BLR', label: 'Biélorussie' },
  { value: 'BEL', label: 'Belgique' },
  { value: 'BLZ', label: 'Belize' },
  { value: 'BEN', label: 'Bénin' },
  { value: 'BMU', label: 'Bermudes' },
  { value: 'BTN', label: 'Bhoutan' },
  { value: 'BOL', label: 'Bolivie (État plurinational de)' },
  { value: 'BES', label: 'Bonaire, Saint-Eustache et Saba' },
  { value: 'BIH', label: 'Bosnie-Herzégovine' },
  { value: 'BWA', label: 'Botswana' },
  { value: 'BVT', label: 'Île Bouvet' },
  { value: 'BRA', label: 'Brésil' },
  { value: 'IOT', label: 'Territoire britannique de l\'océan Indien' },
  { value: 'BRN', label: 'Brunéi Darussalam' },
  { value: 'BGR', label: 'Bulgarie' },
  { value: 'BFA', label: 'Burkina Faso' },
  { value: 'BDI', label: 'Burundi' },
  { value: 'CPV', label: 'Cap-Vert' },
  { value: 'KHM', label: 'Cambodge' },
  { value: 'CMR', label: 'Cameroun' },
  { value: 'CAN', label: 'Canada' },
  { value: 'CYM', label: 'Îles Caïmans (les)' },
  { value: 'CAF', label: 'République centrafricaine (la)' },
  { value: 'TCD', label: 'Tchad' },
  { value: 'CHL', label: 'Chili' },
  { value: 'CHN', label: 'Chine' },
  { value: 'CXR', label: 'Île Christmas' },
  { value: 'CCK', label: 'Îles Cocos (Keeling)' },
  { value: 'COL', label: 'Colombie' },
  { value: 'COM', label: 'Comores (les)' },
  { value: 'COD', label: 'Congo (la République démocratique du)' },
  { value: 'COG', label: 'Congo (le)' },
  { value: 'COK', label: 'Îles Cook (les)' },
  { value: 'CRI', label: 'Costa Rica' },
  { value: 'HRV', label: 'Croatie' },
  { value: 'CUB', label: 'Cuba' },
  { value: 'CUW', label: 'Curaçao' },
  { value: 'CYP', label: 'Chypre' },
  { value: 'CZE', label: 'Tchéquie' },
  { value: 'CIV', label: "Côte d'Ivoire" },
  { value: 'DNK', label: 'Danemark' },
  { value: 'DJI', label: 'Djibouti' },
  { value: 'DMA', label: 'Dominique' },
  { value: 'DOM', label: 'République dominicaine (la)' },
  { value: 'ECU', label: 'Équateur' },
  { value: 'EGY', label: 'Égypte' },
  { value: 'SLV', label: 'El Salvador' },
  { value: 'GNQ', label: 'Guinée équatoriale' },
  { value: 'ERI', label: 'Érythrée' },
  { value: 'EST', label: 'Estonie' },
  { value: 'SWZ', label: 'Eswatini' },
  { value: 'ETH', label: 'Éthiopie' },
  { value: 'FLK', label: 'Îles Malouines (les) [Malvinas]' },
  { value: 'FRO', label: 'Îles Féroé (les)' },
  { value: 'FJI', label: 'Fidji' },
  { value: 'FIN', label: 'Finlande' },
  { value: 'FRA', label: 'France' },
  { value: 'GUF', label: 'Guyane française' },
  { value: 'PYF', label: 'Polynésie française' },
  { value: 'ATF', label: 'Terres australes françaises (les)' },
  { value: 'GAB', label: 'Gabon' },
  { value: 'GMB', label: 'Gambie (la)' },
  { value: 'GEO', label: 'Géorgie' },
  { value: 'DEU', label: 'Allemagne' },
  { value: 'GHA', label: 'Ghana' },
  { value: 'GIB', label: 'Gibraltar' },
  { value: 'GRC', label: 'Grèce' },
  { value: 'GRL', label: 'Groenland' },
  { value: 'GRD', label: 'Grenade' },
  { value: 'GLP', label: 'Guadeloupe' },
  { value: 'GUM', label: 'Guam' },
  { value: 'GTM', label: 'Guatemala' },
  { value: 'GGY', label: 'Guernesey' },
  { value: 'GIN', label: 'Guinée' },
  { value: 'GNB', label: 'Guinée-Bissau' },
  { value: 'GUY', label: 'Guyana' },
  { value: 'HTI', label: 'Haïti' },
  { value: 'HMD', label: 'Îles Heard et MacDonald' },
  { value: 'VAT', label: 'Saint-Siège (le)' },
  { value: 'HND', label: 'Honduras' },
  { value: 'HKG', label: 'Hong Kong' },
  { value: 'HUN', label: 'Hongrie' },
  { value: 'ISL', label: 'Islande' },
  { value: 'IND', label: 'Inde' },
  { value: 'IDN', label: 'Indonésie' },
  { value: 'IRN', label: 'Iran (République islamique d\')' },
  { value: 'IRQ', label: 'Irak' },
  { value: 'IRL', label: 'Irlande' },
  { value: 'IMN', label: 'Île de Man' },
  { value: 'ISR', label: 'Israël' },
  { value: 'ITA', label: 'Italie' },
  { value: 'JAM', label: 'Jamaïque' },
  { value: 'JPN', label: 'Japon' },
  { value: 'JEY', label: 'Jersey' },
  { value: 'JOR', label: 'Jordanie' },
  { value: 'KAZ', label: 'Kazakhstan' },
  { value: 'KEN', label: 'Kenya' },
  { value: 'KIR', label: 'Kiribati' },
  { value: 'PRK', label: 'Corée (la République populaire démocratique de)' },
  { value: 'KOR', label: 'Corée (la République de)' },
  { value: 'KWT', label: 'Koweït' },
  { value: 'KGZ', label: 'Kirghizistan' },
  { value: 'LAO', label: 'République démocratique populaire du Laos (le)' },
  { value: 'LVA', label: 'Lettonie' },
  { value: 'LBN', label: 'Liban' },
  { value: 'LSO', label: 'Lesotho' },
  { value: 'LBR', label: 'Libéria' },
  { value: 'LBY', label: 'Libye' },
  { value: 'LIE', label: 'Liechtenstein' },
  { value: 'LTU', label: 'Lituanie' },
  { value: 'LUX', label: 'Luxembourg' },
  { value: 'MAC', label: 'Macao' },
  { value: 'MDG', label: 'Madagascar' },
  { value: 'MWI', label: 'Malawi' },
  { value: 'MYS', label: 'Malaisie' },
  { value: 'MDV', label: 'Maldives' },
  { value: 'MLI', label: 'Mali' },
  { value: 'MLT', label: 'Malte' },
  { value: 'MHL', label: 'Îles Marshall (les)' },
  { value: 'MTQ', label: 'Martinique' },
  { value: 'MRT', label: 'Mauritanie' },
  { value: 'MUS', label: 'Maurice' },
  { value: 'MYT', label: 'Mayotte' },
  { value: 'MEX', label: 'Mexique' },
  { value: 'FSM', label: 'Micronésie (États fédérés de)' },
  { value: 'MDA', label: 'Moldova (République de)' },
  { value: 'MCO', label: 'Monaco' },
  { value: 'MNG', label: 'Mongolie' },
  { value: 'MNE', label: 'Monténégro' },
  { value: 'MSR', label: 'Montserrat' },
  { value: 'MAR', label: 'Maroc' },
  { value: 'MOZ', label: 'Mozambique' },
  { value: 'MMR', label: 'Myanmar' },
  { value: 'NAM', label: 'Namibie' },
  { value: 'NRU', label: 'Nauru' },
  { value: 'NPL', label: 'Népal' },
  { value: 'NLD', label: 'Pays-Bas (les)' },
  { value: 'NCL', label: 'Nouvelle-Calédonie' },
  { value: 'NZL', label: 'Nouvelle-Zélande' },
  { value: 'NIC', label: 'Nicaragua' },
  { value: 'NER', label: 'Niger (le)' },
  { value: 'NGA', label: 'Nigéria' },
  { value: 'NIU', label: 'Nioué' },
  { value: 'NFK', label: 'Île Norfolk' },
  { value: 'MNP', label: 'Mariannes du Nord (les)' },
  { value: 'NOR', label: 'Norvège' },
  { value: 'OMN', label: 'Oman' },
  { value: 'PAK', label: 'Pakistan' },
  { value: 'PLW', label: 'Palaos' },
  { value: 'PSE', label: 'Palestine, État de' },
  { value: 'PAN', label: 'Panama' },
  { value: 'PNG', label: 'Papouasie-Nouvelle-Guinée' },
  { value: 'PRY', label: 'Paraguay' },
  { value: 'PER', label: 'Pérou' },
  { value: 'PHL', label: 'Philippines (les)' },
  { value: 'PCN', label: 'Pitcairn' },
  { value: 'POL', label: 'Pologne' },
  { value: 'PRT', label: 'Portugal' },
  { value: 'PRI', label: 'Porto Rico' },
  { value: 'QAT', label: 'Qatar' },
  { value: 'MKD', label: 'Macédoine du Nord (la)' },
  { value: 'ROU', label: 'Roumanie' },
  { value: 'RUS', label: 'Fédération de Russie (la)' },
  { value: "RWA", label: "Rwanda" },
  { value: "REU", label: "Réunion" },
  { value: "BLM", label: "Saint-Barthélemy" },
  { value: "SHN", label: "Sainte-Hélène, Ascension et Tristan da Cunha" },
  { value: "KNA", label: "Saint-Kitts-et-Nevis" },
  { value: "LCA", label: "Sainte-Lucie" },
  { value: "MAF", label: "Saint-Martin (partie française)" },
  { value: "SPM", label: "Saint-Pierre-et-Miquelon" },
  { value: "VCT", label: "Saint-Vincent-et-les Grenadines" },
  { value: "WSM", label: "Samoa" },
  { value: "SMR", label: "Saint-Marin" },
  { value: "STP", label: "Sao Tomé-et-Principe" },
  { value: "SAU", label: "Arabie saoudite" },
  { value: "SEN", label: "Sénégal" },
  { value: "SRB", label: "Serbie" },
  { value: "SYC", label: "Seychelles" },
  { value: "SLE", label: "Sierra Leone" },
  { value: "SGP", label: "Singapour" },
  { value: "SXM", label: "Saint-Martin (partie néerlandaise)" },
  { value: "SVK", label: "Slovaquie" },
  { value: "SVN", label: "Slovénie" },
  { value: "SLB", label: "Îles Salomon" },
  { value: "SOM", label: "Somalie" },
  { value: "ZAF", label: "Afrique du Sud" },
  { value: "SGS", label: "Géorgie du Sud et les îles Sandwich du Sud" },
  { value: "SSD", label: "Soudan du Sud" },
  { value: "ESP", label: "Espagne" },
  { value: "LKA", label: "Sri Lanka" },
  { value: "SDN", label: "Soudan (le)" },
  { value: "SUR", label: "Suriname" },
  { value: "SJM", label: "Svalbard et l'Île Jan Mayen" },
  { value: "SWE", label: "Suède" },
  { value: "CHE", label: "Suisse" },
  { value: "SYR", label: "République arabe syrienne" },
  { value: "TWN", label: "Taïwan (Province de Chine)" },
  { value: "TJK", label: "Tadjikistan" },
  { value: "TZA", label: "Tanzanie, République unie de" },
  { value: "THA", label: "Thaïlande" },
  { value: "TLS", label: "Timor-Leste" },
  { value: "TGO", label: "Togo" },
  { value: "TKL", label: "Tokelau" },
  { value: "TON", label: "Tonga" },
  { value: "TTO", label: "Trinité-et-Tobago" },
  { value: "TUN", label: "Tunisie" },
  { value: "TUR", label: "Turquie" },
  { value: "TKM", label: "Turkménistan" },
  { value: "TCA", label: "Îles Turques et Caïques (les)" },
  { value: "TUV", label: "Tuvalu" },
  { value: "UGA", label: "Ouganda" },
  { value: "UKR", label: "Ukraine" },
  { value: "ARE", label: "Émirats arabes unis (les)" },
  { value: "GBR", label: "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)" },
  { value: "UMI", label: "Îles mineures éloignées des États-Unis (les)" },
  { value: "USA", label: "États-Unis d'Amérique (les)" },
  { value: "URY", label: "Uruguay" },
  { value: "UZB", label: "Ouzbékistan" },
  { value: "VUT", label: "Vanuatu" },
  { value: "VEN", label: "Venezuela (République bolivarienne du)" },
  { value: "VNM", label: "Viet Nam" },
  { value: "VGB", label: "Îles Vierges britanniques" },
  { value: "VIR", label: "Îles Vierges des États-Unis" },
  { value: "WLF", label: "Wallis-et-Futuna" },
  { value: "ESH", label: "Sahara occidental" },
  { value: "YEM", label: "Yémen" },
  { value: "ZMB", label: "Zambie" },
  { value: "ZWE", label: "Zimbabwe" },
  { value: "ALA", label: "Îles Åland" }
]

export const countriesES = [
  { value: 'AFG', label: 'Afganistán' },
  { value: 'ALB', label: 'Albania' },
  { value: 'DZA', label: 'Argelia' },
  { value: 'ASM', label: 'Samoa Americana' },
  { value: 'AND', label: 'Andorra' },
  { value: 'AGO', label: 'Angola' },
  { value: 'AIA', label: 'Anguila' },
  { value: 'ATA', label: 'Antártida' },
  { value: 'ATG', label: 'Antigua y Barbuda' },
  { value: 'ARG', label: 'Argentina' },
  { value: 'ARM', label: 'Armenia' },
  { value: 'ABW', label: 'Aruba' },
  { value: 'AUS', label: 'Australia' },
  { value: 'AUT', label: 'Austria' },
  { value: 'AZE', label: 'Azerbaiyán' },
  { value: 'BHS', label: 'Bahamas' },
  { value: 'BHR', label: 'Baréin' },
  { value: 'BGD', label: 'Bangladés' },
  { value: 'BRB', label: 'Barbados' },
  { value: 'BLR', label: 'Bielorrusia' },
  { value: 'BEL', label: 'Bélgica' },
  { value: 'BLZ', label: 'Belice' },
  { value: 'BEN', label: 'Benín' },
  { value: 'BMU', label: 'Bermudas' },
  { value: 'BTN', label: 'Bután' },
  { value: 'BOL', label: 'Bolivia' },
  { value: 'BES', label: 'Bonaire, San Eustaquio y Saba' },
  { value: 'BIH', label: 'Bosnia y Herzegovina' },
  { value: 'BWA', label: 'Botsuana' },
  { value: 'BVT', label: 'Isla Bouvet' },
  { value: 'BRA', label: 'Brasil' },
  { value: 'IOT', label: 'Territorio Británico del Océano Índico' },
  { value: 'BRN', label: 'Brunéi' },
  { value: 'BGR', label: 'Bulgaria' },
  { value: 'BFA', label: 'Burkina Faso' },
  { value: 'BDI', label: 'Burundi' },
  { value: 'CPV', label: 'Cabo Verde' },
  { value: 'KHM', label: 'Camboya' },
  { value: 'CMR', label: 'Camerún' },
  { value: 'CAN', label: 'Canadá' },
  { value: 'CYM', label: 'Islas Caimán' },
  { value: 'CAF', label: 'República Centroafricana' },
  { value: 'TCD', label: 'Chad' },
  { value: 'CHL', label: 'Chile' },
  { value: 'CHN', label: 'China' },
  { value: 'CXR', label: 'Isla de Navidad' },
  { value: 'CCK', label: 'Islas Cocos' },
  { value: 'COL', label: 'Colombia' },
  { value: 'COM', label: 'Comoras' },
  { value: 'COD', label: 'República Democrática del Congo' },
  { value: 'COG', label: 'Congo' },
  { value: 'COK', label: 'Islas Cook' },
  { value: 'CRI', label: 'Costa Rica' },
  { value: 'HRV', label: 'Croacia' },
  { value: 'CUB', label: 'Cuba' },
  { value: 'CUW', label: 'Curazao' },
  { value: 'CYP', label: 'Chipre' },
  { value: 'CZE', label: 'República Checa' },
  { value: 'CIV', label: "Costa de Marfil" },
  { value: 'DNK', label: 'Dinamarca' },
  { value: 'DJI', label: 'Yibuti' },
  { value: 'DMA', label: 'Dominica' },
  { value: 'DOM', label: 'República Dominicana' },
  { value: 'ECU', label: 'Ecuador' },
  { value: 'EGY', label: 'Egipto' },
  { value: 'SLV', label: 'El Salvador' },
  { value: 'GNQ', label: 'Guinea Ecuatorial' },
  { value: 'ERI', label: 'Eritrea' },
  { value: 'EST', label: 'Estonia' },
  { value: 'SWZ', label: 'Eswatini' },
  { value: 'ETH', label: 'Etiopía' },
  { value: 'FLK', label: 'Islas Malvinas (Falkland Islands)' },
  { value: 'FRO', label: 'Islas Feroe (Faroe Islands)' },
  { value: 'FJI', label: 'Fiyi' },
  { value: 'FIN', label: 'Finlandia' },
  { value: 'FRA', label: 'Francia' },
  { value: 'GUF', label: 'Guayana Francesa (French Guiana)' },
  { value: 'PYF', label: 'Polinesia Francesa (French Polynesia)' },
  { value: 'ATF', label: 'Territorios Australes Franceses (French Southern Territories)' },
  { value: 'GAB', label: 'Gabón' },
  { value: 'GMB', label: 'Gambia' },
  { value: 'GEO', label: 'Georgia' },
  { value: 'DEU', label: 'Alemania' },
  { value: 'GHA', label: 'Ghana' },
  { value: 'GIB', label: 'Gibraltar' },
  { value: 'GRC', label: 'Grecia' },
  { value: 'GRL', label: 'Groenlandia (Greenland)' },
  { value: 'GRD', label: 'Granada' },
  { value: 'GLP', label: 'Guadalupe' },
  { value: 'GUM', label: 'Guam' },
  { value: 'GTM', label: 'Guatemala' },
  { value: 'GGY', label: 'Guernsey' },
  { value: 'GIN', label: 'Guinea' },
  { value: 'GNB', label: 'Guinea-Bisáu' },
  { value: 'GUY', label: 'Guyana' },
  { value: 'HTI', label: 'Haití' },
  { value: 'HMD', label: 'Isla Heard e Islas McDonald' },
  { value: 'VAT', label: 'Ciudad del Vaticano (Holy See)' },
  { value: 'HND', label: 'Honduras' },
  { value: 'HKG', label: 'Hong Kong' },
  { value: 'HUN', label: 'Hungría' },
  { value: 'ISL', label: 'Islandia' },
  { value: 'IND', label: 'India' },
  { value: 'IDN', label: 'Indonesia' },
  { value: 'IRN', label: 'Irán' },
  { value: 'IRQ', label: 'Irak' },
  { value: 'IRL', label: 'Irlanda' },
  { value: 'IMN', label: 'Isla de Man (Isle of Man)' },
  { value: 'ISR', label: 'Israel' },
  { value: 'ITA', label: 'Italia' },
  { value: 'JAM', label: 'Jamaica' },
  { value: 'JPN', label: 'Japón' },
  { value: 'JEY', label: 'Jersey' },
  { value: 'JOR', label: 'Jordania' },
  { value: 'KAZ', label: 'Kazajistán' },
  { value: 'KEN', label: 'Kenia' },
  { value: 'KIR', label: 'Kiribati' },
  { value: 'PRK', label: 'Corea del Norte' },
  { value: 'KOR', label: 'Corea del Sur' },
  { value: 'KWT', label: 'Kuwait' },
  { value: 'KGZ', label: 'Kirguistán' },
  { value: 'LAO', label: 'Laos' },
  { value: 'LVA', label: 'Letonia' },
  { value: 'LBN', label: 'Líbano' },
  { value: 'LSO', label: 'Lesoto' },
  { value: 'LBR', label: 'Liberia' },
  { value: 'LBY', label: 'Libia' },
  { value: 'LIE', label: 'Liechtenstein' },
  { value: 'LTU', label: 'Lituania' },
  { value: 'LUX', label: 'Luxemburgo' },
  { value: 'MAC', label: 'Macao' },
  { value: 'MDG', label: 'Madagascar' },
  { value: 'MWI', label: 'Malaui' },
  { value: 'MYS', label: 'Malasia' },
  { value: 'MDV', label: 'Maldivas' },
  { value: 'MLI', label: 'Malí' },
  { value: 'MLT', label: 'Malta' },
  { value: 'MHL', label: 'Islas Marshall' },
  { value: 'MTQ', label: 'Martinica' },
  { value: 'MRT', label: 'Mauritania' },
  { value: 'MUS', label: 'Mauricio' },
  { value: 'MYT', label: 'Mayotte' },
  { value: 'MEX', label: 'México' },
  { value: 'FSM', label: 'Micronesia' },
  { value: 'MDA', label: 'Moldavia' },
  { value: 'MCO', label: 'Mónaco' },
  { value: 'MNG', label: 'Mongolia' },
  { value: 'MNE', label: 'Montenegro' },
  { value: 'MSR', label: 'Montserrat' },
  { value: 'MAR', label: 'Marruecos' },
  { value: 'MOZ', label: 'Mozambique' },
  { value: 'MMR', label: 'Myanmar' },
  { value: 'NAM', label: 'Namibia' },
  { value: 'NRU', label: 'Nauru' },
  { value: 'NPL', label: 'Nepal' },
  { value: 'NLD', label: 'Países Bajos (Netherlands)' },
  { value: 'NCL', label: 'Nueva Caledonia' },
  { value: 'NZL', label: 'Nueva Zelanda' },
  { value: 'NIC', label: 'Nicaragua' },
  { value: 'NER', label: 'Níger' },
  { value: 'NGA', label: 'Nigeria' },
  { value: 'NIU', label: 'Niue' },
  { value: 'NFK', label: 'Isla Norfolk' },
  { value: 'MNP', label: 'Islas Marianas del Norte' },
  { value: 'NOR', label: 'Noruega' },
  { value: 'OMN', label: 'Omán' },
  { value: 'PAK', label: 'Pakistán' },
  { value: 'PLW', label: 'Palaos' },
  { value: 'PSE', label: 'Palestina' },
  { value: 'PAN', label: 'Panamá' },
  { value: 'PNG', label: 'Papúa Nueva Guinea' },
  { value: 'PRY', label: 'Paraguay' },
  { value: 'PER', label: 'Perú' },
  { value: 'PHL', label: 'Filipinas' },
  { value: 'PCN', label: 'Islas Pitcairn' },
  { value: 'POL', label: 'Polonia' },
  { value: 'PRT', label: 'Portugal' },
  { value: 'PRI', label: 'Puerto Rico' },
  { value: 'QAT', label: 'Catar' },
  { value: 'MKD', label: 'Macedonia del Norte' },
  { value: 'ROU', label: 'Rumanía' },
  { value: 'RUS', label: 'Rusia' },
  { value: 'RWA', label: 'Ruanda' },
  { value: 'REU', label: 'Reunión' },
  { value: 'BLM', label: 'San Bartolomé' },
  { value: 'SHN', label: 'Santa Elena, Ascensión y Tristán da Cunha' },
  { value: 'KNA', label: 'San Cristóbal y Nieves' },
  { value: 'LCA', label: 'Santa Lucía' },
  { value: 'MAF', label: 'San Martín' },
  { value: 'SPM', label: 'San Pedro y Miquelón' },
  { value: 'VCT', label: 'San Vicente y las Granadinas' },
  { value: 'WSM', label: 'Samoa' },
  { value: 'SMR', label: 'San Marino' },
  { value: 'STP', label: 'Santo Tomé y Príncipe' },
  { value: 'SAU', label: 'Arabia Saudita' },
  { value: 'SEN', label: 'Senegal' },
  { value: 'SRB', label: 'Serbia' },
  { value: 'SYC', label: 'Seychelles' },
  { value: 'SLE', label: 'Sierra Leona' },
  { value: 'SGP', label: 'Singapur' },
  { value: 'SXM', label: 'Sint Maarten' },
  { value: 'SVK', label: 'Eslovaquia' },
  { value: 'SVN', label: 'Eslovenia' },
  { value: 'SLB', label: 'Islas Salomón' },
  { value: 'SOM', label: 'Somalia' },
  { value: 'ZAF', label: 'Sudáfrica' },
  { value: 'SGS', label: 'Islas Georgias del Sur y Sandwich del Sur' },
  { value: 'SSD', label: 'Sudán del Sur' },
  { value: 'ESP', label: 'España' },
  { value: 'LKA', label: 'Sri Lanka' },
  { value: 'SDN', label: 'Sudán' },
  { value: 'SUR', label: 'Surinam' },
  { value: 'SJM', label: 'Svalbard y Jan Mayen' },
  { value: 'SWE', label: 'Suecia' },
  { value: 'CHE', label: 'Suiza' },
  { value: 'SYR', label: 'República Árabe Siria' },
  { value: 'TWN', label: 'Taiwán' },
  { value: 'TJK', label: 'Tayikistán' },
  { value: 'TZA', label: 'Tanzania' },
  { value: 'THA', label: 'Tailandia' },
  { value: 'TLS', label: 'Timor-Leste' },
  { value: 'TGO', label: 'Togo' },
  { value: 'TKL', label: 'Tokelau' },
  { value: 'TON', label: 'Tonga' },
  { value: 'TTO', label: 'Trinidad y Tobago' },
  { value: 'TUN', label: 'Túnez' },
  { value: 'TUR', label: 'Turquía' },
  { value: 'TKM', label: 'Turkmenistán' },
  { value: 'TCA', label: 'Islas Turcas y Caicos' },
  { value: 'TUV', label: 'Tuvalu' },
  { value: 'UGA', label: 'Uganda' },
  { value: 'UKR', label: 'Ucrania' },
  { value: 'ARE', label: 'Emiratos Árabes Unidos' },
  { value: 'GBR', label: 'Reino Unido' },
  { value: 'UMI', label: 'Islas Ultramarinas Menores de Estados Unidos' },
  { value: 'USA', label: 'Estados Unidos' },
  { value: 'URY', label: 'Uruguay' },
  { value: 'UZB', label: 'Uzbekistán' },
  { value: 'VUT', label: 'Vanuatu' },
  { value: 'VEN', label: 'Venezuela' },
  { value: 'VNM', label: 'Vietnam' },
  { value: 'VGB', label: 'Islas Vírgenes Británicas' },
  { value: 'VIR', label: 'Islas Vírgenes de los Estados Unidos' },
  { value: 'WLF', label: 'Wallis y Futuna' },
  { value: 'ESH', label: 'Sahara Occidental' },
  { value: 'YEM', label: 'Yemen' },
  { value: 'ZMB', label: 'Zambia' },
  { value: 'ZWE', label: 'Zimbabue' },
  { value: 'ALA', label: 'Islas Åland' }
]

export const countriesKR = [
  { value: 'AFG', label: '아프가니스탄' },
  { value: 'ALB', label: '알바니아' },
  { value: 'DZA', label: '알제리' },
  { value: 'ASM', label: '아메리칸 사모아' },
  { value: 'AND', label: '안도라' },
  { value: 'AGO', label: '앙골라' },
  { value: 'AIA', label: '앙귈라' },
  { value: 'ATA', label: '남극 대륙' },
  { value: 'ATG', label: '앤티가 바부다' },
  { value: 'ARG', label: '아르헨티나' },
  { value: 'ARM', label: '아르메니아' },
  { value: 'ABW', label: '아루바' },
  { value: 'AUS', label: '오스트레일리아' },
  { value: 'AUT', label: '오스트리아' },
  { value: 'AZE', label: '아제르바이잔' },
  { value: 'BHS', label: '바하마' },
  { value: 'BHR', label: '바레인' },
  { value: 'BGD', label: '방글라데시' },
  { value: 'BRB', label: '바베이도스' },
  { value: 'BLR', label: '벨라루스' },
  { value: 'BEL', label: '벨기에' },
  { value: 'BLZ', label: '벨리즈' },
  { value: 'BEN', label: '베냉' },
  { value: 'BMU', label: '버뮤다' },
  { value: 'BTN', label: '부탄' },
  { value: 'BOL', label: '볼리비아' },
  { value: 'BES', label: '보네르, 신트 유스타시우스 및 사바' },
  { value: 'BIH', label: '보스니아 헤르체고비나' },
  { value: 'BWA', label: '보츠와나' },
  { value: 'BVT', label: '부베 섬' },
  { value: 'BRA', label: '브라질' },
  { value: 'IOT', label: '영국령 인도양 지역' },
  { value: 'BRN', label: '브루나이 다루살람' },
  { value: 'BGR', label: '불가리아' },
  { value: 'BFA', label: '부르키나 파소' },
  { value: 'BDI', label: '부룬디' },
  { value: 'CPV', label: '카보베르데' },
  { value: 'KHM', label: '캄보디아' },
  { value: 'CMR', label: '카메룬' },
  { value: 'CAN', label: '캐나다' },
  { value: 'CYM', label: '케이맨 제도' },
  { value: 'CAF', label: '중앙 아프리카 공화국' },
  { value: 'TCD', label: '차드' },
  { value: 'CHL', label: '칠레' },
  { value: 'CHN', label: '중국' },
  { value: 'CXR', label: '크리스마스 섬' },
  { value: 'CCK', label: '코코스 제도' },
  { value: 'COL', label: '콜롬비아' },
  { value: 'COM', label: '코모로스' },
  { value: 'COD', label: '콩고 민주 공화국' },
  { value: 'COG', label: '콩고' },
  { value: 'COK', label: '쿡 제도' },
  { value: 'CRI', label: '코스타리카' },
  { value: 'HRV', label: '크로아티아' },
  { value: 'CUB', label: '쿠바' },
  { value: 'CUW', label: '퀴라소' },
  { value: 'CYP', label: '키프로스' },
  { value: 'CZE', label: '체코' },
  { value: 'CIV', label: '코트디부아르' },
  { value: 'DNK', label: '덴마크' },
  { value: 'DJI', label: '지부티' },
  { value: 'DMA', label: '도미니카' },
  { value: 'DOM', label: '도미니카 공화국' },
  { value: 'ECU', label: '에콰도르' },
  { value: 'EGY', label: '이집트' },
  { value: 'SLV', label: '엘살바도르' },
  { value: 'GNQ', label: '적도 기니' },
  { value: 'ERI', label: '에리트레아' },
  { value: 'EST', label: '에스토니아' },
  { value: 'SWZ', label: '에스와티니' },
  { value: 'ETH', label: '에티오피아' },
  { value: 'FLK', label: '포클랜드 제도' },
  { value: 'FRO', label: '페로 제도' },
  { value: 'FJI', label: '피지' },
  { value: 'FIN', label: '핀란드' },
  { value: 'FRA', label: '프랑스' },
  { value: 'GUF', label: '프랑스 기아나' },
  { value: 'PYF', label: '프랑스령 폴리네시아' },
  { value: 'ATF', label: '프랑스령 남방 및 남극 지역' },
  { value: 'GAB', label: '가봉' },
  { value: 'GMB', label: '감비아' },
  { value: 'GEO', label: '조지아' },
  { value: 'DEU', label: '독일' },
  { value: 'GHA', label: '가나' },
  { value: 'GIB', label: '지브롤터' },
  { value: 'GRC', label: '그리스' },
  { value: 'GRL', label: '그린란드' },
  { value: 'GRD', label: '그레나다' },
  { value: 'GLP', label: '과들루프' },
  { value: 'GUM', label: '괌' },
  { value: 'GTM', label: '과테말라' },
  { value: 'GGY', label: '건지' },
  { value: 'GIN', label: '기니' },
  { value: 'GNB', label: '기니비사우' },
  { value: 'GUY', label: '가이아나' },
  { value: 'HTI', label: '아이티' },
  { value: 'HMD', label: '허드 섬과 맥도날드 제도' },
  { value: 'VAT', label: '바티칸 시국' },
  { value: 'HND', label: '온두라스' },
  { value: 'HKG', label: '홍콩' },
  { value: 'HUN', label: '헝가리' },
  { value: 'ISL', label: '아이슬란드' },
  { value: 'IND', label: '인도' },
  { value: 'IDN', label: '인도네시아' },
  { value: 'IRN', label: '이란 (이슬람 공화국)' },
  { value: 'IRQ', label: '이라크' },
  { value: 'IRL', label: '아일랜드' },
  { value: 'IMN', label: '맨 섬' },
  { value: 'ISR', label: '이스라엘' },
  { value: 'ITA', label: '이탈리아' },
  { value: 'JAM', label: '자메이카' },
  { value: 'JPN', label: '일본' },
  { value: 'JEY', label: '저지' },
  { value: 'JOR', label: '요르단' },
  { value: 'KAZ', label: '카자흐스탄' },
  { value: 'KEN', label: '케냐' },
  { value: 'KIR', label: '키리바시' },
  { value: 'PRK', label: '조선 (민주주의인민 공화국)' },
  { value: 'KOR', label: '대한민국' },
  { value: 'KWT', label: '쿠웨이트' },
  { value: 'KGZ', label: '키르기스스탄' },
  { value: 'LAO', label: '라오스' },
  { value: 'LVA', label: '라트비아' },
  { value: 'LBN', label: '레바논' },
  { value: 'LSO', label: '레소토' },
  { value: 'LBR', label: '라이베리아' },
  { value: 'LBY', label: '리비아' },
  { value: 'LIE', label: '리히텐슈타인' },
  { value: 'LTU', label: '리투아니아' },
  { value: 'LUX', label: '룩셈부르크' },
  { value: 'MAC', label: '마카오' },
  { value: 'MDG', label: '마다가스카르' },
  { value: 'MWI', label: '말라위' },
  { value: 'MYS', label: '말레이시아' },
  { value: 'MDV', label: '몰디브' },
  { value: 'MLI', label: '말리' },
  { value: 'MLT', label: '몰타' },
  { value: 'MHL', label: '마셜 제도' },
  { value: 'MTQ', label: '마르티니크' },
  { value: 'MRT', label: '모리타니' },
  { value: 'MUS', label: '모리셔스' },
  { value: 'MYT', label: '마요트' },
  { value: 'MEX', label: '멕시코' },
  { value: 'FSM', label: '미크로네시아 연방' },
  { value: 'MDA', label: '몰도바 공화국' },
  { value: 'MCO', label: '모나코' },
  { value: 'MNG', label: '몽골' },
  { value: 'MNE', label: '몬테네그로' },
  { value: 'MSR', label: '몬트세랫' },
  { value: 'MAR', label: '모로코' },
  { value: 'MOZ', label: '모잠비크' },
  { value: 'MMR', label: '미얀마' },
  { value: 'NAM', label: '나미비아' },
  { value: 'NRU', label: '나우루' },
  { value: 'NPL', label: '네팔' },
  { value: 'NLD', label: '네덜란드' },
  { value: 'NCL', label: '뉴 칼레도니아' },
  { value: 'NZL', label: '뉴질랜드' },
  { value: 'NIC', label: '니카라과' },
  { value: 'NER', label: '니제르' },
  { value: 'NGA', label: '나이지리아' },
  { value: 'NIU', label: '니우에' },
  { value: 'NFK', label: '노퍽섬' },
  { value: 'MNP', label: '북마리아나 제도' },
  { value: 'NOR', label: '노르웨이' },
  { value: 'OMN', label: '오만' },
  { value: 'PAK', label: '파키스탄' },
  { value: 'PLW', label: '팔라우' },
  { value: 'PSE', label: '팔레스타인, 주' },
  { value: 'PAN', label: '파나마' },
  { value: 'PNG', label: '파푸아 뉴기니' },
  { value: 'PRY', label: '파라과이' },
  { value: 'PER', label: '페루' },
  { value: 'PHL', label: '필리핀' },
  { value: 'PCN', label: '핏케언 제도' },
  { value: 'POL', label: '폴란드' },
    { value: 'PRT', label: '포르투갈' },
  { value: 'PRI', label: '푸에르토 리코' },
  { value: 'QAT', label: '카타르' },
  { value: 'MKD', label: '북마케도니아 공화국' },
  { value: 'ROU', label: '루마니아' },
  { value: 'RUS', label: '러시아 연방' },
  { value: 'RWA', label: '르완다' },
  { value: 'REU', label: '레위니옹' },
  { value: 'BLM', label: '생바르텔레미' },
  { value: 'SHN', label: '생헬레나, 아선션 및 트리스탄 다 쿤야' },
  { value: 'KNA', label: '세인트 키츠 네비스' },
  { value: 'LCA', label: '세인트 루시아' },
  { value: 'MAF', label: '생마르탱 (프랑스령)' },
  { value: 'SPM', label: '생피에르 및 미클롱' },
  { value: 'VCT', label: '세인트 빈센트 그레나딘' },
  { value: 'WSM', label: '사모아' },
  { value: 'SMR', label: '산마리노' },
  { value: 'STP', label: '상투메 프린시페' },
  { value: 'SAU', label: '사우디 아라비아' },
  { value: 'SEN', label: '세네갈' },
  { value: 'SRB', label: '세르비아' },
  { value: 'SYC', label: '세이셸' },
  { value: 'SLE', label: '시에라리온' },
  { value: 'SGP', label: '싱가포르' },
  { value: 'SXM', label: '신트마르턴 (네덜란드령)' },
  { value: 'SVK', label: '슬로바키아' },
  { value: 'SVN', label: '슬로베니아' },
  { value: 'SLB', label: '솔로몬 제도' },
  { value: 'SOM', label: '소말리아' },
  { value: 'ZAF', label: '남아프리카' },
  { value: 'SGS', label: '사우스조지사우스샌드위치아일랜드' },
  { value: 'SSD', label: '남수단' },
  { value: 'ESP', label: '스페인' },
  { value: 'LKA', label: '스리랑카' },
  { value: 'SDN', label: '수단' },
  { value: 'SUR', label: '수리남' },
  { value: 'SJM', label: '스발바르 얀마옌' },
  { value: 'SWE', label: '스웨덴' },
  { value: 'CHE', label: '스위스' },
  { value: 'SYR', label: '시리아 아랍 공화국' },
  { value: 'TWN', label: '대만 (중화인민공화국)' },
  { value: 'TJK', label: '타지키스탄' },
  { value: 'TZA', label: '탄자니아 연합 공화국' },
  { value: 'THA', label: '태국' },
  { value: 'TLS', label: '동티모르' },
  { value: 'TGO', label: '토고' },
  { value: 'TKL', label: '토켈라우' },
  { value: 'TON', label: '통가' },
  { value: 'TTO', label: '트리니다드 토바고' },
  { value: 'TUN', label: '튀니지' },
  { value: 'TUR', label: '터키' },
  { value: 'TKM', label: '투르크메니스탄' },
  { value: 'TCA', label: '터크스 케이커스 제도' },
  { value: 'TUV', label: '투발루' },
  { value: 'UGA', label: '우간다' },
  { value: 'UKR', label: '우크라이나' },
  { value: 'ARE', label: '아랍 에미리트 연합' },
  { value: 'GBR', label: '영국' },
  { value: 'UMI', label: '미국령 군소 제도' },
  { value: 'USA', label: '미국' },
  { value: 'URY', label: '우루과이' },
  { value: 'UZB', label: '우즈베키스탄' },
  { value: 'VUT', label: '바누아투' },
  { value: 'VEN', label: '베네수엘라 볼리바르 공화국' },
  { value: 'VNM', label: '베트남' },
  { value: 'VGB', label: '영국령 버진 제도' },
  { value: 'VIR', label: '미국령 버진 제도' },
  { value: 'WLF', label: '왈리스 푸투나' },
  { value: 'ESH', label: '서사하라' },
  { value: 'YEM', label: '예멘' },
  { value: 'ZMB', label: '잠비아' },
  { value: 'ZWE', label: '짐바브웨' },
  { value: 'ALA', label: '올란드 제도' }
]
